# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aboudjem <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/03 14:58:40 by aboudjem          #+#    #+#              #
#    Updated: 2019/01/03 15:08:02 by aboudjem         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

megaphone:	megaphone.cpp
			@clang++ -Wall -Werror -Wextra -o megaphone megaphone.cpp

clean:
			@rm -f megaphone
